-- ==========================================
-- CORREGEDORIA PMESP - SCHEMA COMPLETO
-- Rode os 4 blocos em sequencia no SQL Editor
-- Se der erro em algum, rode os proximos separados (SQL_STEP_1 a 4)
-- ==========================================
